Fastre\CigogneBundle\Entity\Basket:
  type: entity
  id:
    id:
      type: integer
      generator: {strategy: AUTO}
  fields:
    name:
      type: string
      length: 255
    email:
      type: string
      length: 255
    message:
      type: text
      length: 7000
    payment:
      type: string
      length: 10
    token:
      type: string
      length: 255
    lastUpdate:
      type: datetime
    closed:
      type: boolean
  oneToMany:
    elements:
      targetEntity: Gift
      mappedBy: basket
  hasLifecycleCallbacks:
    preUpdate: [setLastUpdateNow]
    
    