Fastre\CigogneBundle\Entity\Code:
  type: entity
  id:
    id:
      type: integer
      generator: {strategy: AUTO}
  indexes:
    - {name: code_word_idx, columns: word}
  fields:
    word:
      type: string
  manyToOne:
    list:
      targetEntity: Listing
      inversedBy: codes