Fastre\CigogneBundle\Entity\Code:
  type: entity
  id:
    id:
      type: integer
      generator: {strategy: AUTO}
  fields:
    word:
      type: string
  manyToOne:
    list:
      targetEntity: Listing
      inversedBy: codes