Fastre\CigogneBundle\Entity\Photo:
  type: entity
  id:
    id:
      type: string
      length: 255
      generator: {strategy: NONE}
  fields:
    type:
      type: string
      length: 5
    creationDate:
      type: datetime
    endAccessDate:
       type: datetime
    tempUrl:
       type: string
       length: 255
      