Fastre\CigogneBundle\Entity\User:
  type: entity
  table: user_table
  id:
    id:
      type: integer
      generator: {strategy: AUTO}
  fields:
    phonenumber:
      type: string
      length: 30
      nullable: true
    paymentPaypalAccepted:
      type: boolean
    paymentPaypalAccount:
      type: string
      nullable: true
    paymentBankAccepted:
      type: boolean
    paymentBankAccountNumber:
      type: string
      nullable: true
    paymentBitcoinAccepted:
      type: boolean
    paymentBitcoinAddress:
      type: string
      nullable: true
      