Fastre\CigogneBundle\Entity\User:
  type: entity
  table: user_table
  id:
    id:
      type: integer
      generator: {strategy: AUTO}
  fields:
    label:
       type: string
       length: 255
    email:
       type: string
       length: 200
    paymentBankAccepted:
      type: boolean
    paymentBankAccountNumber:
      type: string
      nullable: true
  oneToMany:
    lists:
      targetEntity: Listing
      mappedBy: creator
      